### ISSUE TITLE
File is being used by another process (COLI-1216)

### ISSUE THREAD

**Issue by domonkosgabor** [Lombiq/Combinator#22]
I have some entries in the log files:

> 2023-09-27 13:23:12,833 [101] Piedone.Combinator.CombinedResourceManager - Default - Error when combining Style files [https://mysite/controller?somethingId=6865]
> System.IO.IOException: The process cannot access the file 'D:\Sites\mysite\Media\Default\_PiedoneModules\Combinator\Styles\662943427-1.css' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileInfo.Delete()
>    at Piedone.Combinator.Services.CacheFileService.Save(String fingerprint, CombinatorResource resource, ICombinatorSettings settings)
>    at Piedone.Combinator.Services.CombinatorService.<>c__DisplayClass15_0.<Combine>b__0(CombinatorResource combinedResource, List`1 containedResources)
>    at Piedone.Combinator.Services.CombinatorService.Combine(IList`1 resources, String fingerprint, ResourceType resourceType, ICombinatorSettings settings, Boolean saveOnlySharedResources)
>    at Piedone.Combinator.Services.CombinatorService.CombineStylesheets(IList`1 resources, ICombinatorSettings settings)
>    at Piedone.Combinator.CombinedResourceManager.BuildRequiredResources(String stringResourceType)

As you can see it's a CSS file but the same applies to JS files too. I'm not sure what's the root cause of this issue and I haven't found any correlation with clearing the combinator cache so far. This needs further investigation but this log entry happens from time to time.

**Comment by Piedone** [comment]
Related? https://github.com/Lombiq/Combinator/issues/15
